version: '4.20'
services:
  node2:
    build: ./server
    container_name: api_c
    ports:
      -"5000:5000"
    volumes:
      - ./server:/app
      - ./app/node_modules

  client:
    build: ./client
    container_name: client_c
    ports:
      -"3000:3000"
    stdin_open: true
    tty: true
